# Generated by Django 3.2 on 2024-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(choices=[('croissant', 'Croissant ($1)'), ('sandwich', 'Sandwich ($6)'), ('salad', 'Salad ($5)'), ('pastry', 'Pastry ($2)')], max_length=255)),
                ('food_quantity', models.PositiveIntegerField()),
                ('drink_item', models.CharField(choices=[('latte', 'Latte ($3)'), ('coffee', 'Coffee ($2)'), ('tea', 'Tea ($1)'), ('juice', 'Juice ($1)')], max_length=255)),
                ('drink_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
