# Generated by Django 3.2 on 2024-01-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.CharField(choices=[('1 guest', '1 guest'), ('2 guests', '2 guests'), ('3 guests', '3 guests'), ('4 guests', '4 guests'), ('5 guests', '5 guests'), ('6 guests', '6 guests'), ('7 guests', '7 guests'), ('8 guests', '8 guests')], default='1 guest', max_length=50),
        ),
    ]
