# Generated by Django 3.2 on 2024-01-17 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_ordered',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
