# Generated by Django 3.2 on 2024-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Email',
            field=models.EmailField(help_text='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='First_name',
            field=models.CharField(help_text='First name', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Last_name',
            field=models.CharField(help_text='Last name', max_length=50),
        ),
    ]
